"""Runtime configuration. Everything secret comes from the environment; nothing
secret is ever committed or sent to the browser."""

from __future__ import annotations

import os
from functools import lru_cache
from pathlib import Path

APP_DIR = Path(__file__).resolve().parent
LAB_DIR = APP_DIR.parent
CORPUS_DIR = LAB_DIR / "corpus"
INDEX_PATH = CORPUS_DIR / "index.json"


def _load_dotenv() -> None:
    """Tiny .env reader. Avoids a dependency, and Vercel injects real env vars anyway."""
    for name in (".env.local", ".env"):
        path = LAB_DIR / name
        if not path.exists():
            continue
        for raw in path.read_text(encoding="utf-8").splitlines():
            line = raw.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            if key and key not in os.environ:
                os.environ[key] = value


_load_dotenv()


def _env(name: str, default: str = "") -> str:
    """Whitespace-stripped read.

    Values set through a CLI pipe or pasted into a dashboard field routinely arrive with a
    trailing newline. A stray "\\n" inside an API key becomes an invalid HTTP header value and
    fails the request in a way whose error message points nowhere near the cause.
    """
    return os.environ.get(name, default).strip()


class Settings:
    # --- model ---------------------------------------------------------------
    gemini_api_key: str = _env("GEMINI_API_KEY")
    model_id: str = _env("MODEL_ID", "gemini-3.1-flash-lite") or "gemini-3.1-flash-lite"
    embed_model_id: str = _env("EMBED_MODEL_ID", "gemini-embedding-001") or "gemini-embedding-001"
    embed_dims: int = int(_env("EMBED_DIMS", "768") or 768)
    gemini_base: str = "https://generativelanguage.googleapis.com/v1beta"

    # --- persistence ---------------------------------------------------------
    supabase_url: str = _env("SUPABASE_URL").rstrip("/")
    supabase_secret: str = _env("SUPABASE_SECRET_KEY")

    # --- signing -------------------------------------------------------------
    # base64url-encoded raw 32-byte Ed25519 seed. Generated by scripts/gen_keys.py.
    signing_seed: str = _env("SIGNING_SEED")

    # --- behaviour -----------------------------------------------------------
    request_timeout: float = float(_env("REQUEST_TIMEOUT", "45") or 45)
    max_claims: int = int(_env("MAX_CLAIMS", "12") or 12)
    reference_clock: str = _env("REFERENCE_CLOCK")  # ISO date; blank = now

    @property
    def has_model(self) -> bool:
        return bool(self.gemini_api_key)

    @property
    def has_store(self) -> bool:
        return bool(self.supabase_url and self.supabase_secret)


@lru_cache(maxsize=1)
def settings() -> Settings:
    return Settings()
