"""Runtime configuration. Everything secret comes from the environment; nothing
secret is ever committed or sent to the browser."""

from __future__ import annotations

import os
from functools import lru_cache
from pathlib import Path

APP_DIR = Path(__file__).resolve().parent
LAB_DIR = APP_DIR.parent
CORPUS_DIR = LAB_DIR / "corpus"
INDEX_PATH = CORPUS_DIR / "index.json"


def _load_dotenv() -> None:
    """Tiny .env reader. Avoids a dependency, and Vercel injects real env vars anyway."""
    for name in (".env.local", ".env"):
        path = LAB_DIR / name
        if not path.exists():
            continue
        for raw in path.read_text(encoding="utf-8").splitlines():
            line = raw.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            if key and key not in os.environ:
                os.environ[key] = value


_load_dotenv()


class Settings:
    # --- model ---------------------------------------------------------------
    gemini_api_key: str = os.environ.get("GEMINI_API_KEY", "")
    model_id: str = os.environ.get("MODEL_ID", "gemini-3.1-flash-lite")
    embed_model_id: str = os.environ.get("EMBED_MODEL_ID", "gemini-embedding-001")
    embed_dims: int = int(os.environ.get("EMBED_DIMS", "768"))
    gemini_base: str = "https://generativelanguage.googleapis.com/v1beta"

    # --- persistence ---------------------------------------------------------
    supabase_url: str = os.environ.get("SUPABASE_URL", "").rstrip("/")
    supabase_secret: str = os.environ.get("SUPABASE_SECRET_KEY", "")

    # --- signing -------------------------------------------------------------
    # base64url-encoded raw 32-byte Ed25519 seed. Generated by scripts/gen_keys.py.
    signing_seed: str = os.environ.get("SIGNING_SEED", "")

    # --- behaviour -----------------------------------------------------------
    request_timeout: float = float(os.environ.get("REQUEST_TIMEOUT", "45"))
    max_claims: int = int(os.environ.get("MAX_CLAIMS", "12"))
    reference_clock: str = os.environ.get("REFERENCE_CLOCK", "")  # ISO date; blank = now

    @property
    def has_model(self) -> bool:
        return bool(self.gemini_api_key)

    @property
    def has_store(self) -> bool:
        return bool(self.supabase_url and self.supabase_secret)


@lru_cache(maxsize=1)
def settings() -> Settings:
    return Settings()
